title: Welcome to naftee.com (brettvac.github.io)
description: Joomla! extensions to make your life easier as an authority with a money site
url: "https://naftee.com"
baseurl: ""
github_username: brettvac
author:
  name: "Brett Vachon"
google_analytics: "G-DP5DG417G7" 
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
